version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: sampleapp:latest
    container_name: the-ups-mon
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
    expose:
      - 80
